/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/workspace.theme.ts
 * Command: astryx theme build theme/workspace.theme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/**
 * workspace theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { workspaceTheme } from './workspace';
 *   import './workspace.css';
 */
export const workspaceTheme = {
  name: 'workspace',
  __built: true,
  tokens: {
    "--color-accent": "#A3B565",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "#29321E",
    "--color-neutral": "light-dark(#1B1C131A, #E2E4D633)",
    "--color-background-surface": "light-dark(#FDF8E2, #282E21)",
    "--color-background-body": "light-dark(#FDF8E2, #20251A)",
    "--color-overlay": "light-dark(#1B1C1366, #1B1C1399)",
    "--color-overlay-hover": "light-dark(#1B1C130D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#1B1C131A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#D0D6A3, #3A442E)",
    "--color-text-primary": "light-dark(#29321E, #FDF8E2)",
    "--color-text-secondary": "light-dark(#555F42, #D2D5BC)",
    "--color-text-disabled": "light-dark(#8F9281, #5D6050)",
    "--color-text-accent": "light-dark(#52682D, #C7D794)",
    "--color-icon-accent": "light-dark(#52682D, #C7D794)",
    "--color-icon-primary": "light-dark(#29321E, #FDF8E2)",
    "--color-icon-secondary": "light-dark(#555F42, #D2D5BC)",
    "--color-icon-disabled": "light-dark(#8F9281, #5D6050)",
    "--color-background-card": "light-dark(#D0D6A3, #303827)",
    "--color-background-popover": "light-dark(#FBFEF0, #2F3127)",
    "--color-background-inverted": "light-dark(#1B1C13, #FBFEF0)",
    "--color-border": "light-dark(#D1D6B8, #596348)",
    "--color-border-emphasized": "light-dark(#8F9281, #676A59)",
    "--color-skeleton": "light-dark(#AAAD9B, #454839)",
    "--color-track": "light-dark(#AAAD9B, #454839)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.5rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.6875rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.1875rem",
    "--font-size-xl": "1.4375rem",
    "--font-size-2xl": "1.75rem",
    "--font-size-3xl": "2.0625rem",
    "--font-size-4xl": "2.5rem",
    "--font-size-5xl": "3rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.4286",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-bold)",
    "--text-heading-2-leading": "1.3913",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.4737",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.4545",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.5",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4737",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.5",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.5",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.25",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.3",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2121",
    "--radius-none": "0px",
    "--radius-inner": "5px",
    "--radius-element": "10px",
    "--radius-container": "15px",
    "--radius-page": "35px",
    "--radius-chat": "35px",
    "--radius-full": "9999px",
    "--duration-fast-min": "105ms",
    "--duration-fast": "140ms",
    "--duration-fast-max": "185ms",
    "--duration-medium-min": "180ms",
    "--duration-medium": "240ms",
    "--duration-medium-max": "320ms",
    "--duration-slow-min": "300ms",
    "--duration-slow": "400ms",
    "--duration-slow-max": "535ms",
    "--font-family-body": "var(--font-geist-sans), system-ui, sans-serif",
    "--font-family-heading": "var(--font-geist-sans), system-ui, sans-serif",
    "--focus-outline-color": "light-dark(#52682D, #C7D794)",
    "--size-element-md": "44px",
    "--size-element-lg": "48px"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "app-shell-sidenav": {
      "base": {
        "borderInlineEndColor": "var(--color-text-secondary)"
      }
    },
    "app-shell-header": {
      "base": {
        "--color-border": "var(--color-text-secondary)"
      }
    },
    "side-nav": {
      "mode:topbar": {
        "display": "none"
      },
      "base": {
        "backgroundColor": "#A3B565",
        "--color-text-primary": "#29321E",
        "--color-text-secondary": "#354123",
        "--color-icon-primary": "#29321E",
        "--color-icon-secondary": "#354123",
        "--color-border": "#788C49",
        "--color-background-surface": "#A3B565",
        "--color-background-muted": "#D0D6A3",
        "--color-accent": "#FDF8E2",
        "--color-text-accent": "#FDF8E2",
        "--color-icon-accent": "#FDF8E2",
        "--color-accent-muted": "#D0D6A3",
        "--color-on-accent": "#29321E"
      }
    },
    "side-nav-item": {
      "base": {
        "minHeight": "var(--size-element-lg)"
      },
      "selected": {
        "backgroundColor": "var(--color-accent)",
        "color": "var(--color-on-accent)",
        "--color-text-primary": "var(--color-on-accent)",
        "--color-icon-primary": "var(--color-on-accent)",
        "--color-text-accent": "var(--color-on-accent)",
        "--color-icon-accent": "var(--color-on-accent)"
      }
    },
    "card": {
      "base": {
        "borderColor": "var(--color-border)"
      }
    },
    "table-header-cell": {
      "base": {
        "backgroundColor": "var(--color-background-muted)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
