/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/workspace.theme.ts
 * Command: astryx theme build theme/workspace.theme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const workspaceTheme: DefinedTheme;
